/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "qchat.h"

clist *join_1_svc(cname *argp, struct svc_req *rqstp) {

	static clist clients;



	return(&result);
}

int *send_1_svc(msg_send *argp, struct svc_req *rqstp) {

	static int result;



	return(&result);
}

int *exit_1_svc(msg_send *argp, struct svc_req *rqstp) {

	static int result;


	return(&result);
}

int *heartbeat_1_svc(int *argp, struct svc_req *rqstp) {

	static int result;


	return(&result);
}
