/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "qchat.h"

clientlist *
join_1(argp, rqstp)
	cname *argp;
	struct svc_req *rqstp;
{

	static clientlist result;

	// Add to clientlist
	// return current clientlist
	// multicast new member msg, seq#

	return(&result);
}

int *
send_1(argp, rqstp)
	msg_send *argp;
	struct svc_req *rqstp;
{

	static int result;

	// assign seq#
	// multicast to clients, on fail/retry:
	// 		remove client from clist
	//		multicast exist msg, seq# 

	return(&result);
}

int *
exit_1(argp, rqstp)
	msg_send *argp;
	struct svc_req *rqstp;
{

	static int result;

	// assign seq#
	// remove from clist, isLeaderCheck:
	// 		pickNewLeader
	//		multicast new leader
	// multicast exist msg, seq#

	return(&result);
}

