/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "qchat.h"

bool_t
xdr_msg_send(XDR *xdrs, msg_send *objp)
{

	if (!xdr_string(xdrs, objp, MAX_MSG_LEN))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_uname(XDR *xdrs, uname *objp)
{

	if (!xdr_string(xdrs, objp, MAX_USR_LEN))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cname(XDR *xdrs, cname *objp)
{

	if (!xdr_uname(xdrs, &objp->userNames))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->ip_port, ~0))
		return (FALSE);
	if (!xdr_bool(xdrs, &objp->leader_flag))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_msg_recv(XDR *xdrs, msg_recv *objp)
{

	if (!xdr_msg_send(xdrs, &objp->msg_sent))
		return (FALSE);
	if (!xdr_uname(xdrs, &objp->user_sent))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->seq_num))
		return (FALSE);
	return (TRUE);
}
