/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "qchat.h"

bool_t
xdr_msg_send(XDR *xdrs, msg_send *objp)
{

	if (!xdr_string(xdrs, objp, MAX_MSG_LEN))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_uname(XDR *xdrs, uname *objp)
{

	if (!xdr_string(xdrs, objp, MAX_USR_LEN))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ip_port(XDR *xdrs, ip_port *objp)
{

	if (!xdr_string(xdrs, objp, MAX_IP_LEN))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cname(XDR *xdrs, cname *objp)
{

	if (!xdr_uname(xdrs, &objp->userName))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->hostname.hostname_val, (u_int *)&objp->hostname.hostname_len, ~0, sizeof(ip_port), (xdrproc_t)xdr_ip_port))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->leader_flag))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_msg_recv(XDR *xdrs, msg_recv *objp)
{

	if (!xdr_msg_send(xdrs, &objp->msg_sent))
		return (FALSE);
	if (!xdr_uname(xdrs, &objp->user_sent))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->seq_num))
		return (FALSE);
	return (TRUE);
}
