/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _QCHAT_H_RPCGEN
#define _QCHAT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_MSG_LEN 512
#define MAX_USR_LEN 32
#define MAX_IP_LEN 32
#define BUFLEN 556

typedef char *msg_send;

typedef char *uname;

typedef char *hoststr;

enum msg_type_t {
	TEXT = 0,
	NEWUSER = 1,
	USEREXIT = 2,
	ELECTION = 3,
};
typedef enum msg_type_t msg_type_t;

enum status_code {
	JSUCCESS = 0,
	JFAILURE = 1,
	UNAMEINUSE = 2,
	UNAMEINVALID = 3,
};
typedef enum status_code status_code;

struct cname {
	uname userName;
	hoststr hostname;
	int lport;
	int leader_flag;
};
typedef struct cname cname;


struct clist {
	struct {
		u_int clientlist_len;
		cname *clientlist_val;
	} clientlist;
};
typedef struct clist clist;

struct msg_recv {
	msg_send msg_sent;
	uname user_sent;
	u_int seq_num;
	msg_type_t msg_type;
};
typedef struct msg_recv msg_recv;

#define QCHAT 0x20000001
#define QCHATVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define JOIN 1
extern  int * join_1(cname *, CLIENT *);
extern  int * join_1_svc(cname *, struct svc_req *);
#define SEND 2
extern  int * send_1(msg_recv *, CLIENT *);
extern  int * send_1_svc(msg_recv *, struct svc_req *);
#define EXIT 3
extern  int * exit_1(msg_recv *, CLIENT *);
extern  int * exit_1_svc(msg_recv *, struct svc_req *);
#define REDELIVER 4
extern  msg_recv * redeliver_1(u_int *, CLIENT *);
extern  msg_recv * redeliver_1_svc(u_int *, struct svc_req *);
#define HEARTBEAT 5
extern  u_int * heartbeat_1(u_int *, CLIENT *);
extern  u_int * heartbeat_1_svc(u_int *, struct svc_req *);
#define SHUTDOWNSERV 6
extern  void * shutdownserv_1(void *, CLIENT *);
extern  void * shutdownserv_1_svc(void *, struct svc_req *);
extern int qchat_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define JOIN 1
extern  int * join_1();
extern  int * join_1_svc();
#define SEND 2
extern  int * send_1();
extern  int * send_1_svc();
#define EXIT 3
extern  int * exit_1();
extern  int * exit_1_svc();
#define REDELIVER 4
extern  msg_recv * redeliver_1();
extern  msg_recv * redeliver_1_svc();
#define HEARTBEAT 5
extern  u_int * heartbeat_1();
extern  u_int * heartbeat_1_svc();
#define SHUTDOWNSERV 6
extern  void * shutdownserv_1();
extern  void * shutdownserv_1_svc();
extern int qchat_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_msg_send (XDR *, msg_send*);
extern  bool_t xdr_uname (XDR *, uname*);
extern  bool_t xdr_hoststr (XDR *, hoststr*);
extern  bool_t xdr_msg_type_t (XDR *, msg_type_t*);
extern  bool_t xdr_status_code (XDR *, status_code*);
extern  bool_t xdr_cname (XDR *, cname*);
extern  bool_t xdr_cname (XDR *, cname*);
extern  bool_t xdr_clist (XDR *, clist*);
extern  bool_t xdr_msg_recv (XDR *, msg_recv*);

#else /* K&R C */
extern bool_t xdr_msg_send ();
extern bool_t xdr_uname ();
extern bool_t xdr_hoststr ();
extern bool_t xdr_msg_type_t ();
extern bool_t xdr_status_code ();
extern bool_t xdr_cname ();
extern bool_t xdr_cname ();
extern bool_t xdr_clist ();
extern bool_t xdr_msg_recv ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_QCHAT_H_RPCGEN */
